import { Button } from "@chakra-ui/button";
import { Input } from "@chakra-ui/input";
import { Text } from "@chakra-ui/layout";
import { Heading } from "@chakra-ui/layout";
import { Flex } from "@chakra-ui/layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext, useEffect } from "react";
import NavigationBar from "../src/Components/index/NavigationBar";
import Colors from "../src/Constants/Colors";
import NavLoginButtonContext from "../src/Context/NavLogInButtonContext";
import useWindowSize from "../src/CustomHooks/UseWindows";
import styles from "../styles/Home.module.css";

export default function Login() {
  const getWindowSize = useWindowSize();
  const navLoginButtonContext = useContext(NavLoginButtonContext);
  useEffect(() => {
    // console.log(navLoginButtonContext.isLoggedIn);
  }, []);
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex {...styleProps.indexWrapper}>
        <Heading color={Colors.black}>Login</Heading>
        <Flex
          w={
            getWindowSize.width < 960
              ? getWindowSize.width * 0.7
              : getWindowSize.width * 0.3
          }
          {...styleProps.formCardContainer}
        >
          <Input placeholder="Account ID" marginBottom="3" autoFocus />
          <Input placeholder="Password" type="password" />
          <Text
            marginBottom="5"
            textAlign="right"
            fontSize="13"
            fontWeight="bold"
            cursor="pointer"
            onClick={() => {
              // Transfer this function when if the login success
              navLoginButtonContext.handleLoggedInState();
            }}
          >
            Forgot Password?
          </Text>
          <Link
            href={navLoginButtonContext.isLoggedIn ? "/dashboard" : "/login"}
          >
            <Button
              backgroundColor={Colors.green}
              color={Colors.white}
              colorScheme="cyan"
              onClick={() => {
                console.log(navLoginButtonContext.isLoggedIn);
              }}
            >
              LOG IN
            </Button>
          </Link>
        </Flex>
      </Flex>
    </>
  );
}

const styleProps = {
  indexWrapper: {
    height: "100vh",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    bgColor: Colors.white,
  },
  formCardContainer: {
    flexDirection: "column",
    bgColor: "#ffffff",
    marginTop: "10",
    marginBottom: "16",
    borderRadius: "lg",
    shadow: "lg",
    padding: "5",
  },
};
